### ISSUE TITLE
Unknown event type 79

### ISSUE THREAD

**Issue by marxin** [google/autofdo#43]
Hello.

I see probably the same as discussed in #37. My env is:

```
$ uname -a
Linux marxinbox 4.10.8-1-default #1 SMP PREEMPT Fri Mar 31 17:16:00 UTC 2017 (ea9dcd4) x86_64 x86_64 x86_64 GNU/Linux

$ perf --version
perf version 4.8.4
```
I tested both autotools 0.15 and current trunk, both behave the same:
There's content of my perf.data file

```
$ perf script -i ~/Downloads/indir-call-prof.perf.data | head -n20
Failed to open /home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01, continuing without symbols
 indir-call-prof 13298  6018.058609:          1 cpu/event=0xC4,umask=0x20/pu:      7f2bac7ffca7 _dl_start+0xa7 (/lib64/ld-2.25.so)
 indir-call-prof 13298  6018.058614:          1 cpu/event=0xC4,umask=0x20/pu:      7f2bac7ffca3 _dl_start+0xa3 (/lib64/ld-2.25.so)
 indir-call-prof 13298  6018.058617:          7 cpu/event=0xC4,umask=0x20/pu:      7f2bac7ffc98 _dl_start+0x98 (/lib64/ld-2.25.so)
 indir-call-prof 13298  6018.058620:         76 cpu/event=0xC4,umask=0x20/pu:      7f2bac7ffd59 _dl_start+0x159 (/lib64/ld-2.25.so)
 indir-call-prof 13298  6018.058625:        813 cpu/event=0xC4,umask=0x20/pu:      7f2bac812808 _dl_sysdep_start+0x48 (/lib64/ld-2.25.so)
 indir-call-prof 13298  6018.058629:       6330 cpu/event=0xC4,umask=0x20/pu:      7f2bac811aa0 __tunables_init+0x60 (/lib64/ld-2.25.so)
 indir-call-prof 13298  6018.058638:      52447 cpu/event=0xC4,umask=0x20/pu:      7f2bac811b13 __tunables_init+0xd3 (/lib64/ld-2.25.so)
 indir-call-prof 13298  6018.058813:     217332 cpu/event=0xC4,umask=0x20/pu:            400510 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.058928:     229110 cpu/event=0xC4,umask=0x20/pu:            400510 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.059049:     262561 cpu/event=0xC4,umask=0x20/pu:            400510 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.059187:     297514 cpu/event=0xC4,umask=0x20/pu:            400422 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.059344:     327593 cpu/event=0xC4,umask=0x20/pu:            400408 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.059515:     352199 cpu/event=0xC4,umask=0x20/pu:            400422 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.059699:     372308 cpu/event=0xC4,umask=0x20/pu:            400510 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.059894:     388913 cpu/event=0xC4,umask=0x20/pu:            400408 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.060097:     402754 cpu/event=0xC4,umask=0x20/pu:            400422 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.060307:     414372 cpu/event=0xC4,umask=0x20/pu:            400408 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.060524:     424153 cpu/event=0xC4,umask=0x20/pu:            400408 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.060745:     432436 cpu/event=0xC4,umask=0x20/pu:            400510 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
 indir-call-prof 13298  6018.060971:     439451 cpu/event=0xC4,umask=0x20/pu:            400422 [unknown] (/home/marxin/Programming/gcc/objdir/gcc/testsuite/gcc/indir-call-prof.x01)
```

[indir-call-prof.perf.data.zip.tar.gz](https://github.com/google/autofdo/files/916412/indir-call-prof.perf.data.zip.tar.gz)

Thanks for help.
Martin

**Comment by xry111** [comment]
It's also breaking my GCC tree-prof testsuite.

**Comment by jingoo** [comment]
I also have the same issue 'Unknown event type 79'.
Is there anyone who fixed this problem?

**Comment by jingoo** [comment]
I found that the number '79' means PERF_RECORD_TIME_CONV.
Also, the patch for PERF_RECORD_TIME_CONV was already merged into the 'perf' source code in Linux kernel.
(https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=46bc29b970f0011a9099077f1db8f3540aa829fe)
I hope that my opinion is helpful.

**Comment by marxin** [comment]
You're right, but problem is that the event is not recognized by autofdo. I've just wrote email to Andi Kleen. Hope he'll help us.

**Comment by marxin** [comment]
It's fixed on master.

**Comment by MartinNowak** [comment]
Hello @marxin, I'm still running into this issue. Are you sure the fix was merged and landed in the github repo?

**Comment by danielcdh** [comment]
Yes, it should have been fixed by https://github.com/google/autofdo/commit/b46d431e35f38e6b604aae54f63779a15843019b

**Comment by jacksgt** [comment]
Weird, I still have this issue.
* Linux: 4.13.0-rc6+ (from git master)
* Perf: 4.13.rc6.g647081 (from git master)
* AutoFDO: master HEAD (153c17801358fb9692ed1ec7d0065057d0541eb8)

```
$ ~/autofdo/create_gcov --binary=./simple --profile=perf.inj --gcov=sort.gcov -gcov_version=1
E0830 05:50:06.959956  5916 perf_reader.cc:996] Unsupported event type 79
F0830 05:50:06.960176  5916 perf_parser.cc:240] Check failed: reader_.ReadPerfSampleInfo(*parsed_event.raw_event, &sample_info) 
*** Check failure stack trace: ***
    @     0x559ed4a6238e  google::LogMessage::Flush()
    @     0x559ed4a65359  google::LogMessageFatal::~LogMessageFatal()
    @     0x559ed4a58ba2  quipper::PerfParser::MaybeSortParsedEvents()
    @     0x559ed4a5a2c9  quipper::PerfParser::ProcessEvents()
    @     0x559ed4a5ba4c  quipper::PerfParser::ParseRawEvents()
    @     0x559ed4a3c2d0  autofdo::PerfDataSampleReader::Append()
    @     0x559ed4a3b793  autofdo::SampleReader::ReadAndSetTotalCount()
    @     0x559ed4a34332  autofdo::ProfileCreator::ReadSample()
    @     0x559ed4a35202  autofdo::ProfileCreator::CreateProfile()
    @     0x559ed4a2570d  main
    @     0x7f58fb47f2b1  (unknown)
    @     0x559ed4a26f0a  _start
    @              (nil)  (unknown)
Aborted
```

**Comment by VictorRodriguez** [comment]
This patch worked for me with linux 4.12, autofdo master and perf 4.12 : 
https://github.com/andikleen/autofdo/commit/de91694d07debde8862d4c68abf9bd60f8dd9cea

thanks

**Comment by jacksgt** [comment]
@VictorRodriguez Thanks for the hint, works like a charm! 👍
